# Generated by Django 2.0.7 on 2018-11-23 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beyblade_burst_web_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='energylayers',
            name='abbreviation',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AddField(
            model_name='energylayers',
            name='name',
            field=models.CharField(default='Wah', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='energylayers',
            name='weight',
            field=models.DecimalField(decimal_places=3, default=10, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='forgedisks',
            name='abbreviation',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AddField(
            model_name='forgedisks',
            name='name',
            field=models.CharField(default='sigh', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='forgedisks',
            name='weight',
            field=models.DecimalField(decimal_places=3, default=10.0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='performancetips',
            name='abbreviation',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AddField(
            model_name='performancetips',
            name='name',
            field=models.CharField(default='Please stop', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='performancetips',
            name='weight',
            field=models.DecimalField(decimal_places=3, default=5.1, max_digits=10),
            preserve_default=False,
        ),
    ]
