# Generated by Django 2.0.7 on 2018-11-23 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beyblade_burst_web_app', '0002_auto_20181123_1720'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PerformanceTips',
            new_name='EnergyLayer',
        ),
        migrations.RenameModel(
            old_name='EnergyLayers',
            new_name='ForgeDisk',
        ),
        migrations.RenameModel(
            old_name='ForgeDisks',
            new_name='PerformanceTip',
        ),
    ]
