# Generated by Django 2.0.7 on 2018-11-23 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beyblade_burst_web_app', '0003_auto_20181123_1728'),
    ]

    operations = [
        migrations.AddField(
            model_name='energylayer',
            name='product_code',
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.AddField(
            model_name='forgedisk',
            name='product_code',
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.AddField(
            model_name='performancetip',
            name='product_code',
            field=models.CharField(blank=True, max_length=8),
        ),
    ]
