# Generated by Django 2.0.7 on 2018-11-28 22:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('beyblade_burst_web_app', '0005_auto_20181123_1905'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='energylayer',
            options={'verbose_name': 'Energy Layer', 'verbose_name_plural': 'Energy Layers'},
        ),
        migrations.AlterModelOptions(
            name='forgedisk',
            options={'verbose_name': 'Forge Disk', 'verbose_name_plural': 'Forge Disks'},
        ),
        migrations.AlterModelOptions(
            name='performancetip',
            options={'verbose_name': 'Performance Tip', 'verbose_name_plural': 'Performance Tips'},
        ),
        migrations.AddField(
            model_name='energylayer',
            name='aliases',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='energylayer',
            name='initial_release',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='energylayer',
            name='japanese_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='energylayer',
            name='spin_direction',
            field=models.CharField(choices=[('LT', 'Left'), ('RT', 'Right')], default='RT', max_length=2),
        ),
        migrations.AddField(
            model_name='energylayer',
            name='system',
            field=models.CharField(blank=True, choices=[('BR', 'Burst'), ('DR', 'Dual Layer'), ('GD', 'God Layer'), ('CZ', 'Cho Z')], max_length=2),
        ),
    ]
