# Generated by Django 2.0.7 on 2018-12-03 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beyblade_burst_web_app', '0007_energylayer_part_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Combination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('disk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beyblade_burst_web_app.ForgeDisk')),
            ],
        ),
        migrations.AlterField(
            model_name='energylayer',
            name='abbreviation',
            field=models.CharField(max_length=8, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AddField(
            model_name='combination',
            name='layer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beyblade_burst_web_app.EnergyLayer'),
        ),
        migrations.AddField(
            model_name='combination',
            name='tip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beyblade_burst_web_app.PerformanceTip'),
        ),
    ]
