# Generated by Django 2.0.7 on 2018-12-04 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beyblade_burst_web_app', '0008_auto_20181203_1818'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='combination',
            options={'verbose_name': 'Combination', 'verbose_name_plural': 'Combinations'},
        ),
        migrations.RemoveField(
            model_name='combination',
            name='disk',
        ),
        migrations.AddField(
            model_name='combination',
            name='disk',
            field=models.ManyToManyField(to='beyblade_burst_web_app.ForgeDisk'),
        ),
        migrations.RemoveField(
            model_name='combination',
            name='layer',
        ),
        migrations.AddField(
            model_name='combination',
            name='layer',
            field=models.ManyToManyField(to='beyblade_burst_web_app.EnergyLayer'),
        ),
        migrations.AlterField(
            model_name='combination',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.RemoveField(
            model_name='combination',
            name='tip',
        ),
        migrations.AddField(
            model_name='combination',
            name='tip',
            field=models.ManyToManyField(to='beyblade_burst_web_app.PerformanceTip'),
        ),
        migrations.AlterField(
            model_name='forgedisk',
            name='abbreviation',
            field=models.CharField(max_length=8, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='performancetip',
            name='abbreviation',
            field=models.CharField(max_length=8, primary_key=True, serialize=False),
        ),
    ]
