# Generated by Django 2.0.7 on 2018-12-04 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beyblade_burst_web_app', '0010_auto_20181204_2116'),
    ]

    operations = [
        migrations.AddField(
            model_name='combination',
            name='disk',
            field=models.ManyToManyField(to='beyblade_burst_web_app.ForgeDisk'),
        ),
        migrations.AddField(
            model_name='combination',
            name='layer',
            field=models.ManyToManyField(to='beyblade_burst_web_app.EnergyLayer'),
        ),
        migrations.AddField(
            model_name='combination',
            name='tip',
            field=models.ManyToManyField(to='beyblade_burst_web_app.PerformanceTip'),
        ),
    ]
