# Generated by Django 2.0.7 on 2018-12-04 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beyblade_burst_web_app', '0013_auto_20181204_2122'),
    ]

    operations = [
        migrations.AddField(
            model_name='combination',
            name='disk',
            field=models.ForeignKey(default='A', on_delete=django.db.models.deletion.CASCADE, to='beyblade_burst_web_app.ForgeDisk'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='combination',
            name='layer',
            field=models.ForeignKey(default='A', on_delete=django.db.models.deletion.CASCADE, to='beyblade_burst_web_app.EnergyLayer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='combination',
            name='tip',
            field=models.ForeignKey(default='A', on_delete=django.db.models.deletion.CASCADE, to='beyblade_burst_web_app.PerformanceTip'),
            preserve_default=False,
        ),
    ]
