# Generated by Django 2.1.1 on 2018-12-06 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beyblade_burst_web_app', '0015_auto_20181206_2208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='energylayer',
            name='spin_direction',
            field=models.CharField(choices=[('Left', 'Left'), ('Right', 'Right')], default='Right', max_length=5),
        ),
    ]
