# Generated by Django 2.1.1 on 2019-04-01 01:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beyblade_burst_web_app', '0016_auto_20181206_2209'),
    ]

    operations = [
        migrations.CreateModel(
            name='BeybladePart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abbreviation', models.CharField(blank=True, max_length=8)),
                ('name', models.CharField(max_length=30, unique=True)),
                ('japanese_name', models.CharField(blank=True, max_length=50)),
                ('aliases', models.CharField(blank=True, max_length=50)),
                ('product_code', models.CharField(blank=True, max_length=8)),
                ('initial_release', models.DateField(blank=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=3, max_digits=10)),
                ('part_image', models.ImageField(blank=True, upload_to='parts/layers/')),
                ('part_type', models.CharField(choices=[('LAYER', 'Energy Layer'), ('DISK', 'Forge Disk'), ('TIP', 'Performance Tip'), ('FRAME', 'Disk Frame'), ('CHIP', 'Gatinko Chip'), ('WEIGHT', 'Gatinko Weight'), ('BASE', 'Gatinko Base')], max_length=30)),
                ('system', models.CharField(blank=True, choices=[('BURST', 'Burst'), ('DUAL_LAYER', 'Dual Layer'), ('GOD_SYS', 'God Layer'), ('CHO_Z', 'Cho Zetsu'), ('GT', 'Gatinko')], max_length=30)),
                ('spin_direction', models.CharField(blank=True, choices=[('LEFT', 'Left'), ('RIGHT', 'Right')], max_length=5)),
            ],
            options={
                'verbose_name': 'Part',
                'verbose_name_plural': 'Parts',
            },
        ),
        migrations.AlterField(
            model_name='combination',
            name='disk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disks', related_query_name='disk', to='beyblade_burst_web_app.BeybladePart'),
        ),
        migrations.AlterField(
            model_name='combination',
            name='layer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='layers', related_query_name='layer', to='beyblade_burst_web_app.BeybladePart'),
        ),
        migrations.AlterField(
            model_name='combination',
            name='tip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tips', related_query_name='tip', to='beyblade_burst_web_app.BeybladePart'),
        ),
        migrations.DeleteModel(
            name='EnergyLayer',
        ),
        migrations.DeleteModel(
            name='ForgeDisk',
        ),
        migrations.DeleteModel(
            name='PerformanceTip',
        ),
    ]
