# Generated by Django 2.1.1 on 2019-06-05 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beyblade_burst_web_app', '0017_auto_20190331_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beybladepart',
            name='spin_direction',
            field=models.CharField(blank=True, choices=[('LEFT', 'Left'), ('RIGHT', 'Right'), ('DUAL', 'Dual')], max_length=5),
        ),
    ]
