# Generated by Django 2.2.2 on 2019-06-08 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beyblade_burst_web_app', '0019_auto_20190605_0055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beybladepart',
            name='aliases',
            field=models.TextField(blank=True, max_length=50),
        ),
    ]
